#!/usr/bin/env bash

set -euo pipefail

script_dir=$(cd "$(dirname "$0")" && pwd)
repo_dir=$(cd "$script_dir/.." && pwd)
bin_dir="$HOME/.local/bin"
marker="# generated by hiho_scripts"

bash_names=(
  bash_run
  counter_pr
  get_contributors
  get_pr_detail_comments_review_threads
  get_pr_review_thread_by_comment_id
  git_remote_clean
  new_branch
  pbcopy_files
  show_diff_with_default_branch
  clipexe
  stash_and_pr
)

python_cmds=(
  hiho_ai_code
  hiho_ai_code_checkout_pr
  hiho_ai_code_counter_pr
  hiho_get_github_template
  hiho_update_voicevox_pr_snapshots
  hiho_generate_password
)

python_files=(
  ai_code.py
  ai_code_checkout_pr.py
  ai_code_counter_pr.py
  get_github_template.py
  update_voicevox_pr_snapshots.py
  generate_password.py
)

install_wrapper() {
  local target="$1"
  local content="$2"
  local name
  name=$(basename "$target")

  if [[ -f "$target" ]]; then
    if ! grep -qF "$marker" "$target"; then
      echo "警告: $name は hiho_scripts 以外の既存ファイルです。スキップします。"
      return 0
    fi
    if [[ "$(cat "$target")" == "$content" ]]; then
      echo "✓ $name は既に最新です"
      return 0
    fi
  fi

  echo "$content" > "$target"
  chmod +x "$target"
  echo "✓ $name を配置しました"
}

# TODO: 旧方式 (bashrc への source 追記) からの移行が完了したら remove_old_shell_entries とその呼び出しを削除する
remove_old_shell_entries() {
  local config_file="$1"
  [[ ! -f "$config_file" ]] && return 0

  if ! grep -qF "# hiho_scripts" "$config_file"; then
    return 0
  fi

  local backup="${config_file}.hiho.bak.$(date +'%Y%m%d-%H%M%S')"
  cp "$config_file" "$backup"

  local temp_file
  temp_file=$(mktemp)
  awk '
    /^# hiho_scripts$/ { skip = 1; next }
    skip && /^source / { skip = 0; next }
    { print }
  ' "$config_file" > "$temp_file"
  mv "$temp_file" "$config_file"

  echo "✓ $(basename "$config_file") の旧設定を削除しました"
  echo "  バックアップ: $backup"
}

check_path() {
  case ":$PATH:" in
    *":$bin_dir:"*) return 0 ;;
  esac

  echo ""
  echo "警告: $bin_dir が PATH に含まれていません。"
  echo "以下の 1 行を設定ファイルに追記してください:"
  echo ""
  echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
  echo ""

  local os
  os=$(uname -s)
  case "$os" in
    MINGW* | MSYS* | CYGWIN*)
      echo "追記先の推奨: ~/.bash_profile"
      ;;
    Darwin)
      echo "追記先の推奨: zsh ユーザーは ~/.zshrc、bash ユーザーは ~/.bash_profile"
      ;;
    *)
      echo "追記先の推奨: ~/.bashrc"
      ;;
  esac
}

main() {
  echo "hiho_scripts を $bin_dir に同期します..."
  echo ""

  mkdir -p "$bin_dir"

  for name in "${bash_names[@]}"; do
    local source_file="$repo_dir/${name}.bash"
    local func="hiho_${name}"
    local content="#!/usr/bin/env bash
${marker}
source \"${source_file}\"
${func} \"\$@\""
    install_wrapper "$bin_dir/$func" "$content"
  done

  for i in "${!python_cmds[@]}"; do
    local cmd="${python_cmds[$i]}"
    local py_file="${python_files[$i]}"
    local source_file="$repo_dir/${py_file}"
    local content="#!/usr/bin/env bash
${marker}
exec \"${source_file}\" \"\$@\""
    install_wrapper "$bin_dir/$cmd" "$content"
  done

  echo ""
  remove_old_shell_entries "$HOME/.bashrc"
  remove_old_shell_entries "$HOME/.zshrc"

  check_path

  echo ""
  echo "完了しました。新しいシェルを開くとコマンドが使用できます。"
}

main
